{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "903a4d88-988c-4f62-abfb-ab7080d733f8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Sandeep\\anaconda3\\Lib\\site-packages\\sklearn\\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.4.2 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:\n",
      "https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations\n",
      "  warnings.warn(\n",
      "C:\\Users\\Sandeep\\anaconda3\\Lib\\site-packages\\sklearn\\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.4.2 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:\n",
      "https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations\n",
      "  warnings.warn(\n",
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5000\n",
      "Press CTRL+C to quit\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, request, jsonify, render_template_string\n",
    "import pickle\n",
    "import pandas as pd\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# Load model\n",
    "with open(\"C:\\\\ai_insonmia\\\\insomnia_model.pkl\", 'rb') as f:\n",
    "    model = pickle.load(f)\n",
    "\n",
    "HTML = '''<!DOCTYPE html>\n",
    "<html lang=\"en\">\n",
    "<head>\n",
    "<meta charset=\"UTF-8\"/>\n",
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n",
    "<title>Insomnia Risk Assessment</title>\n",
    "<link href=\"https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:wght@300;400;500&display=swap\" rel=\"stylesheet\"/>\n",
    "<style>\n",
    "  :root {\n",
    "    --bg: #0a0a0f;\n",
    "    --surface: #12121a;\n",
    "    --card: #1a1a26;\n",
    "    --border: #2a2a3d;\n",
    "    --accent: #7c6af7;\n",
    "    --accent2: #f76a8c;\n",
    "    --green: #4ade80;\n",
    "    --yellow: #fbbf24;\n",
    "    --red: #f87171;\n",
    "    --text: #e8e8f0;\n",
    "    --muted: #6b6b8a;\n",
    "  }\n",
    "  * { margin: 0; padding: 0; box-sizing: border-box; }\n",
    "  body {\n",
    "    background: var(--bg);\n",
    "    color: var(--text);\n",
    "    font-family: 'DM Sans', sans-serif;\n",
    "    min-height: 100vh;\n",
    "    overflow-x: hidden;\n",
    "  }\n",
    "  /* Animated background */\n",
    "  body::before {\n",
    "    content: '';\n",
    "    position: fixed;\n",
    "    top: -50%;\n",
    "    left: -50%;\n",
    "    width: 200%;\n",
    "    height: 200%;\n",
    "    background: radial-gradient(ellipse at 20% 20%, rgba(124,106,247,0.08) 0%, transparent 50%),\n",
    "                radial-gradient(ellipse at 80% 80%, rgba(247,106,140,0.06) 0%, transparent 50%);\n",
    "    animation: bgShift 10s ease-in-out infinite alternate;\n",
    "    z-index: 0;\n",
    "    pointer-events: none;\n",
    "  }\n",
    "  @keyframes bgShift {\n",
    "    0% { transform: translate(0,0); }\n",
    "    100% { transform: translate(2%, 2%); }\n",
    "  }\n",
    "  .container {\n",
    "    max-width: 780px;\n",
    "    margin: 0 auto;\n",
    "    padding: 48px 24px;\n",
    "    position: relative;\n",
    "    z-index: 1;\n",
    "  }\n",
    "  header { text-align: center; margin-bottom: 48px; }\n",
    "  .badge {\n",
    "    display: inline-block;\n",
    "    background: rgba(124,106,247,0.15);\n",
    "    border: 1px solid rgba(124,106,247,0.3);\n",
    "    color: var(--accent);\n",
    "    font-family: 'Syne', sans-serif;\n",
    "    font-size: 11px;\n",
    "    font-weight: 600;\n",
    "    letter-spacing: 0.15em;\n",
    "    text-transform: uppercase;\n",
    "    padding: 6px 16px;\n",
    "    border-radius: 100px;\n",
    "    margin-bottom: 20px;\n",
    "  }\n",
    "  h1 {\n",
    "    font-family: 'Syne', sans-serif;\n",
    "    font-size: clamp(28px, 5vw, 44px);\n",
    "    font-weight: 800;\n",
    "    line-height: 1.1;\n",
    "    margin-bottom: 12px;\n",
    "    background: linear-gradient(135deg, #e8e8f0 0%, var(--accent) 100%);\n",
    "    -webkit-background-clip: text;\n",
    "    -webkit-text-fill-color: transparent;\n",
    "    background-clip: text;\n",
    "  }\n",
    "  .subtitle {\n",
    "    color: var(--muted);\n",
    "    font-size: 15px;\n",
    "    font-weight: 300;\n",
    "    line-height: 1.6;\n",
    "  }\n",
    "  .form-card {\n",
    "    background: var(--card);\n",
    "    border: 1px solid var(--border);\n",
    "    border-radius: 20px;\n",
    "    padding: 36px;\n",
    "    margin-bottom: 24px;\n",
    "  }\n",
    "  .section-title {\n",
    "    font-family: 'Syne', sans-serif;\n",
    "    font-size: 12px;\n",
    "    font-weight: 700;\n",
    "    letter-spacing: 0.12em;\n",
    "    text-transform: uppercase;\n",
    "    color: var(--accent);\n",
    "    margin-bottom: 20px;\n",
    "    display: flex;\n",
    "    align-items: center;\n",
    "    gap: 8px;\n",
    "  }\n",
    "  .section-title::after {\n",
    "    content: '';\n",
    "    flex: 1;\n",
    "    height: 1px;\n",
    "    background: var(--border);\n",
    "  }\n",
    "  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }\n",
    "  @media(max-width: 560px) { .grid { grid-template-columns: 1fr; } }\n",
    "  .field { display: flex; flex-direction: column; gap: 8px; }\n",
    "  label {\n",
    "    font-size: 13px;\n",
    "    font-weight: 500;\n",
    "    color: var(--muted);\n",
    "    letter-spacing: 0.02em;\n",
    "  }\n",
    "  .input-wrap { position: relative; }\n",
    "  input[type=range] {\n",
    "    -webkit-appearance: none;\n",
    "    width: 100%;\n",
    "    height: 4px;\n",
    "    background: var(--border);\n",
    "    border-radius: 4px;\n",
    "    outline: none;\n",
    "    margin: 8px 0 4px;\n",
    "  }\n",
    "  input[type=range]::-webkit-slider-thumb {\n",
    "    -webkit-appearance: none;\n",
    "    width: 18px;\n",
    "    height: 18px;\n",
    "    background: var(--accent);\n",
    "    border-radius: 50%;\n",
    "    cursor: pointer;\n",
    "    box-shadow: 0 0 0 4px rgba(124,106,247,0.2);\n",
    "    transition: box-shadow 0.2s;\n",
    "  }\n",
    "  input[type=range]:hover::-webkit-slider-thumb {\n",
    "    box-shadow: 0 0 0 6px rgba(124,106,247,0.3);\n",
    "  }\n",
    "  .range-labels {\n",
    "    display: flex;\n",
    "    justify-content: space-between;\n",
    "    font-size: 11px;\n",
    "    color: var(--muted);\n",
    "  }\n",
    "  .val-badge {\n",
    "    display: inline-block;\n",
    "    background: rgba(124,106,247,0.15);\n",
    "    color: var(--accent);\n",
    "    font-family: 'Syne', sans-serif;\n",
    "    font-weight: 700;\n",
    "    font-size: 13px;\n",
    "    padding: 2px 10px;\n",
    "    border-radius: 6px;\n",
    "    min-width: 36px;\n",
    "    text-align: center;\n",
    "  }\n",
    "  .toggle-group {\n",
    "    display: flex;\n",
    "    background: var(--surface);\n",
    "    border: 1px solid var(--border);\n",
    "    border-radius: 10px;\n",
    "    overflow: hidden;\n",
    "  }\n",
    "  .toggle-group input { display: none; }\n",
    "  .toggle-group label {\n",
    "    flex: 1;\n",
    "    text-align: center;\n",
    "    padding: 10px;\n",
    "    font-size: 13px;\n",
    "    font-weight: 500;\n",
    "    color: var(--muted);\n",
    "    cursor: pointer;\n",
    "    transition: all 0.2s;\n",
    "    margin: 0;\n",
    "  }\n",
    "  .toggle-group input:checked + label {\n",
    "    background: var(--accent);\n",
    "    color: white;\n",
    "  }\n",
    "  .submit-btn {\n",
    "    width: 100%;\n",
    "    padding: 16px;\n",
    "    background: linear-gradient(135deg, var(--accent), var(--accent2));\n",
    "    border: none;\n",
    "    border-radius: 12px;\n",
    "    color: white;\n",
    "    font-family: 'Syne', sans-serif;\n",
    "    font-size: 15px;\n",
    "    font-weight: 700;\n",
    "    letter-spacing: 0.05em;\n",
    "    cursor: pointer;\n",
    "    transition: all 0.3s;\n",
    "    margin-top: 8px;\n",
    "    position: relative;\n",
    "    overflow: hidden;\n",
    "  }\n",
    "  .submit-btn::before {\n",
    "    content: '';\n",
    "    position: absolute;\n",
    "    top: 0; left: -100%;\n",
    "    width: 100%; height: 100%;\n",
    "    background: linear-gradient(90deg, transparent, rgba(255,255,255,0.1), transparent);\n",
    "    transition: left 0.5s;\n",
    "  }\n",
    "  .submit-btn:hover::before { left: 100%; }\n",
    "  .submit-btn:hover { transform: translateY(-2px); box-shadow: 0 8px 30px rgba(124,106,247,0.4); }\n",
    "  .submit-btn:active { transform: translateY(0); }\n",
    "\n",
    "  /* Result */\n",
    "  #result {\n",
    "    display: none;\n",
    "    background: var(--card);\n",
    "    border: 1px solid var(--border);\n",
    "    border-radius: 20px;\n",
    "    padding: 36px;\n",
    "    text-align: center;\n",
    "    animation: slideUp 0.5s cubic-bezier(0.34,1.56,0.64,1);\n",
    "  }\n",
    "  @keyframes slideUp {\n",
    "    from { opacity: 0; transform: translateY(30px) scale(0.97); }\n",
    "    to   { opacity: 1; transform: translateY(0) scale(1); }\n",
    "  }\n",
    "  .risk-icon { font-size: 56px; margin-bottom: 16px; display: block; }\n",
    "  .risk-label {\n",
    "    font-family: 'Syne', sans-serif;\n",
    "    font-size: 28px;\n",
    "    font-weight: 800;\n",
    "    margin-bottom: 8px;\n",
    "  }\n",
    "  .risk-desc {\n",
    "    color: var(--muted);\n",
    "    font-size: 14px;\n",
    "    margin-bottom: 28px;\n",
    "    line-height: 1.6;\n",
    "  }\n",
    "  .prob-bars { display: flex; flex-direction: column; gap: 12px; text-align: left; }\n",
    "  .prob-row { display: flex; flex-direction: column; gap: 6px; }\n",
    "  .prob-top { display: flex; justify-content: space-between; font-size: 13px; }\n",
    "  .prob-track {\n",
    "    height: 6px;\n",
    "    background: var(--border);\n",
    "    border-radius: 6px;\n",
    "    overflow: hidden;\n",
    "  }\n",
    "  .prob-fill {\n",
    "    height: 100%;\n",
    "    border-radius: 6px;\n",
    "    transition: width 1s cubic-bezier(0.34,1.56,0.64,1);\n",
    "    width: 0;\n",
    "  }\n",
    "  .low-fill  { background: var(--green); }\n",
    "  .mid-fill  { background: var(--yellow); }\n",
    "  .high-fill { background: var(--red); }\n",
    "  .advice {\n",
    "    margin-top: 28px;\n",
    "    background: var(--surface);\n",
    "    border-radius: 12px;\n",
    "    padding: 20px;\n",
    "    text-align: left;\n",
    "  }\n",
    "  .advice-title {\n",
    "    font-family: 'Syne', sans-serif;\n",
    "    font-size: 12px;\n",
    "    font-weight: 700;\n",
    "    letter-spacing: 0.1em;\n",
    "    text-transform: uppercase;\n",
    "    color: var(--accent);\n",
    "    margin-bottom: 12px;\n",
    "  }\n",
    "  .advice ul { list-style: none; display: flex; flex-direction: column; gap: 8px; }\n",
    "  .advice li { font-size: 13px; color: var(--muted); display: flex; gap: 8px; align-items: flex-start; }\n",
    "  .advice li::before { content: '→'; color: var(--accent); flex-shrink: 0; }\n",
    "  .reset-btn {\n",
    "    margin-top: 20px;\n",
    "    background: transparent;\n",
    "    border: 1px solid var(--border);\n",
    "    color: var(--muted);\n",
    "    padding: 10px 24px;\n",
    "    border-radius: 8px;\n",
    "    cursor: pointer;\n",
    "    font-size: 13px;\n",
    "    transition: all 0.2s;\n",
    "  }\n",
    "  .reset-btn:hover { border-color: var(--accent); color: var(--accent); }\n",
    "</style>\n",
    "</head>\n",
    "<body>\n",
    "<div class=\"container\">\n",
    "  <header>\n",
    "    <div class=\"badge\">AI-Powered Assessment</div>\n",
    "    <h1>Insomnia Risk<br/>Analyzer</h1>\n",
    "    <p class=\"subtitle\">Answer a few questions about your lifestyle<br/>and our AI will assess your insomnia risk.</p>\n",
    "  </header>\n",
    "\n",
    "  <div class=\"form-card\">\n",
    "    <div class=\"section-title\">Sleep & Body</div>\n",
    "    <div class=\"grid\">\n",
    "      <div class=\"field\">\n",
    "        <label>Age: <span class=\"val-badge\" id=\"age-val\">25</span></label>\n",
    "        <div class=\"input-wrap\">\n",
    "          <input type=\"range\" id=\"age\" min=\"18\" max=\"65\" value=\"25\"\n",
    "                 oninput=\"document.getElementById('age-val').textContent=this.value\"/>\n",
    "          <div class=\"range-labels\"><span>18</span><span>65</span></div>\n",
    "        </div>\n",
    "      </div>\n",
    "      <div class=\"field\">\n",
    "        <label>Sleep Hours/Night: <span class=\"val-badge\" id=\"sleep-val\">7</span></label>\n",
    "        <div class=\"input-wrap\">\n",
    "          <input type=\"range\" id=\"sleep_hours\" min=\"1\" max=\"10\" step=\"0.5\" value=\"7\"\n",
    "                 oninput=\"document.getElementById('sleep-val').textContent=this.value\"/>\n",
    "          <div class=\"range-labels\"><span>1h</span><span>10h</span></div>\n",
    "        </div>\n",
    "      </div>\n",
    "      <div class=\"field\">\n",
    "        <label>Stress Level: <span class=\"val-badge\" id=\"stress-val\">5</span></label>\n",
    "        <div class=\"input-wrap\">\n",
    "          <input type=\"range\" id=\"stress_level\" min=\"1\" max=\"10\" value=\"5\"\n",
    "                 oninput=\"document.getElementById('stress-val').textContent=this.value\"/>\n",
    "          <div class=\"range-labels\"><span>Low</span><span>High</span></div>\n",
    "        </div>\n",
    "      </div>\n",
    "      <div class=\"field\">\n",
    "        <label>Exercise Days/Week: <span class=\"val-badge\" id=\"ex-val\">3</span></label>\n",
    "        <div class=\"input-wrap\">\n",
    "          <input type=\"range\" id=\"exercise_days\" min=\"0\" max=\"7\" value=\"3\"\n",
    "                 oninput=\"document.getElementById('ex-val').textContent=this.value\"/>\n",
    "          <div class=\"range-labels\"><span>0</span><span>7</span></div>\n",
    "        </div>\n",
    "      </div>\n",
    "    </div>\n",
    "\n",
    "    <div class=\"section-title\" style=\"margin-top:28px\">Habits</div>\n",
    "    <div class=\"grid\">\n",
    "      <div class=\"field\">\n",
    "        <label>Screen Time Before Bed: <span class=\"val-badge\" id=\"screen-val\">2</span>h</label>\n",
    "        <input type=\"range\" id=\"screen_time\" min=\"0\" max=\"6\" step=\"0.5\" value=\"2\"\n",
    "               oninput=\"document.getElementById('screen-val').textContent=this.value\"/>\n",
    "        <div class=\"range-labels\"><span>0h</span><span>6h</span></div>\n",
    "      </div>\n",
    "      <div class=\"field\">\n",
    "        <label>Caffeine Cups/Day: <span class=\"val-badge\" id=\"caff-val\">2</span></label>\n",
    "        <input type=\"range\" id=\"caffeine_cups\" min=\"0\" max=\"8\" value=\"2\"\n",
    "               oninput=\"document.getElementById('caff-val').textContent=this.value\"/>\n",
    "        <div class=\"range-labels\"><span>0</span><span>8</span></div>\n",
    "      </div>\n",
    "      <div class=\"field\">\n",
    "        <label>Nap During Day?</label>\n",
    "        <div class=\"toggle-group\">\n",
    "          <input type=\"radio\" name=\"nap\" id=\"nap0\" value=\"0\" checked/>\n",
    "          <label for=\"nap0\">No</label>\n",
    "          <input type=\"radio\" name=\"nap\" id=\"nap1\" value=\"1\"/>\n",
    "          <label for=\"nap1\">Yes</label>\n",
    "        </div>\n",
    "      </div>\n",
    "      <div class=\"field\">\n",
    "        <label>Irregular Sleep Schedule?</label>\n",
    "        <div class=\"toggle-group\">\n",
    "          <input type=\"radio\" name=\"irreg\" id=\"irreg0\" value=\"0\" checked/>\n",
    "          <label for=\"irreg0\">No</label>\n",
    "          <input type=\"radio\" name=\"irreg\" id=\"irreg1\" value=\"1\"/>\n",
    "          <label for=\"irreg1\">Yes</label>\n",
    "        </div>\n",
    "      </div>\n",
    "    </div>\n",
    "\n",
    "    <button class=\"submit-btn\" onclick=\"predict()\">Analyze My Sleep Risk →</button>\n",
    "  </div>\n",
    "\n",
    "  <div id=\"result\"></div>\n",
    "</div>\n",
    "\n",
    "<script>\n",
    "const advice = {\n",
    "  0: [\"Maintain your current sleep schedule\",\"Keep up the regular exercise routine\",\"Limit caffeine after 2pm as a precaution\",\"Continue limiting screen time before bed\"],\n",
    "  1: [\"Try to get 7-8 hours of sleep consistently\",\"Reduce screen time 1 hour before bed\",\"Cut caffeine intake after noon\",\"Add light exercise 3-4 days a week\",\"Practice relaxation techniques before sleep\"],\n",
    "  2: [\"Consult a sleep specialist immediately\",\"Set a strict consistent sleep/wake schedule\",\"Avoid all caffeine after 12pm\",\"No screens at least 2 hours before bed\",\"Try meditation or deep breathing exercises\",\"Consider cognitive behavioral therapy for insomnia\"]\n",
    "};\n",
    "\n",
    "async function predict() {\n",
    "  const btn = document.querySelector('.submit-btn');\n",
    "  btn.textContent = 'Analyzing...';\n",
    "  btn.disabled = true;\n",
    "\n",
    "  const payload = {\n",
    "    age: +document.getElementById('age').value,\n",
    "    sleep_hours: +document.getElementById('sleep_hours').value,\n",
    "    screen_time: +document.getElementById('screen_time').value,\n",
    "    caffeine_cups: +document.getElementById('caffeine_cups').value,\n",
    "    exercise_days: +document.getElementById('exercise_days').value,\n",
    "    stress_level: +document.getElementById('stress_level').value,\n",
    "    nap_during_day: +document.querySelector('input[name=nap]:checked').value,\n",
    "    irregular_schedule: +document.querySelector('input[name=irreg]:checked').value\n",
    "  };\n",
    "\n",
    "  try {\n",
    "    const res = await fetch('/predict', {\n",
    "      method: 'POST',\n",
    "      headers: {'Content-Type':'application/json'},\n",
    "      body: JSON.stringify(payload)\n",
    "    });\n",
    "    const data = await res.json();\n",
    "    showResult(data);\n",
    "  } catch(e) {\n",
    "    alert('Error: ' + e.message);\n",
    "  }\n",
    "\n",
    "  btn.textContent = 'Analyze My Sleep Risk →';\n",
    "  btn.disabled = false;\n",
    "}\n",
    "\n",
    "function showResult(data) {\n",
    "  const icons = {0:'😴', 1:'😟', 2:'🚨'};\n",
    "  const labels = {0:'Low Risk', 1:'Medium Risk', 2:'High Risk'};\n",
    "  const colors = {0:'#4ade80', 1:'#fbbf24', 2:'#f87171'};\n",
    "  const descs = {\n",
    "    0: 'Your lifestyle habits support healthy sleep. Keep it up!',\n",
    "    1: 'Some habits may be affecting your sleep quality. Small changes can help.',\n",
    "    2: 'Your lifestyle patterns strongly suggest insomnia risk. Please seek help.'\n",
    "  };\n",
    "\n",
    "  const r = data.risk;\n",
    "  const el = document.getElementById('result');\n",
    "  el.style.display = 'block';\n",
    "  el.innerHTML = `\n",
    "    <span class=\"risk-icon\">${icons[r]}</span>\n",
    "    <div class=\"risk-label\" style=\"color:${colors[r]}\">${labels[r]}</div>\n",
    "    <div class=\"risk-desc\">${descs[r]}</div>\n",
    "    <div class=\"prob-bars\">\n",
    "      <div class=\"prob-row\">\n",
    "        <div class=\"prob-top\"><span style=\"color:#4ade80\">🟢 Low Risk</span><span>${data.probabilities[0]}%</span></div>\n",
    "        <div class=\"prob-track\"><div class=\"prob-fill low-fill\" id=\"low-bar\"></div></div>\n",
    "      </div>\n",
    "      <div class=\"prob-row\">\n",
    "        <div class=\"prob-top\"><span style=\"color:#fbbf24\">🟡 Medium Risk</span><span>${data.probabilities[1]}%</span></div>\n",
    "        <div class=\"prob-track\"><div class=\"prob-fill mid-fill\" id=\"mid-bar\"></div></div>\n",
    "      </div>\n",
    "      <div class=\"prob-row\">\n",
    "        <div class=\"prob-top\"><span style=\"color:#f87171\">🔴 High Risk</span><span>${data.probabilities[2]}%</span></div>\n",
    "        <div class=\"prob-track\"><div class=\"prob-fill high-fill\" id=\"high-bar\"></div></div>\n",
    "      </div>\n",
    "    </div>\n",
    "    <div class=\"advice\">\n",
    "      <div class=\"advice-title\">Recommendations</div>\n",
    "      <ul>${advice[r].map(a => `<li>${a}</li>`).join('')}</ul>\n",
    "    </div>\n",
    "    <button class=\"reset-btn\" onclick=\"document.getElementById('result').style.display='none'\">Reassess ↺</button>\n",
    "  `;\n",
    "  el.scrollIntoView({behavior:'smooth'});\n",
    "  setTimeout(() => {\n",
    "    document.getElementById('low-bar').style.width  = data.probabilities[0] + '%';\n",
    "    document.getElementById('mid-bar').style.width  = data.probabilities[1] + '%';\n",
    "    document.getElementById('high-bar').style.width = data.probabilities[2] + '%';\n",
    "  }, 100);\n",
    "}\n",
    "</script>\n",
    "</body>\n",
    "</html>'''\n",
    "\n",
    "@app.route('/')\n",
    "def index():\n",
    "    return render_template_string(HTML)\n",
    "\n",
    "@app.route('/predict', methods=['POST'])\n",
    "def predict():\n",
    "    d = request.json\n",
    "    df = pd.DataFrame([d])\n",
    "    risk = int(model.predict(df)[0])\n",
    "    probs = model.predict_proba(df)[0]\n",
    "    return jsonify({\n",
    "        'risk': risk,\n",
    "        'probabilities': [round(p*100,1) for p in probs]\n",
    "    })\n",
    "\n",
    "# NEW - works everywhere\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=False, use_reloader=False, port=5000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c57e9c3c-44d9-4ffa-a807-c1d9bdcb28a4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ceddb9cb-21c8-4a3b-ac5e-8e867bfed333",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d957a57f-566a-4955-a3ea-017b2480d287",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
